# Generated by Django 4.0 on 2022-01-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='Comments',
            new_name='comments',
        ),
    ]
